spring:
  datasource:
    url: jdbc:h2:mem:test-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/museum-dev
          # Point to the URI containing the public key so that our Resource Server can verify the tokens’ integrity.
          jwk-set-uri: http://localhost:9000/realms/museum-dev/protocol/openid-connect/certs
  application:
    name: museum