spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/museifier
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${museifier.oauth2.issuer-uri}
          # Point to the URI containing the public key so that our Resource Server can verify the tokens’ integrity.
          jwk-set-uri: ${museifier.oauth2.jwk-uri}
  application:
    name: museifier-dev
  jpa:
    hibernate:
      # Disable Hibernate database initialization because we want to use 'schema.sql'
      ddl-auto: none
  sql:
    init:
      mode: always

# ====== Disabled in prod ======
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: ${museifier.oauth2.client-id}
      scopes: ${museifier.oauth2.scopes}
# ==============================

museifier:
  oauth2:
    client-id: museifier-dev
    scopes: "openid"
    issuer-uri: http://localhost:9000/realms/museifier-dev
    token-uri: http://localhost:9000/realms/museifier-dev/protocol/openid-connect/token
    jwk-uri: http://localhost:9000/realms/museifier-dev/protocol/openid-connect/certs
debug: true