server:
  tomcat:
    threads:
      # This is a demo app so it doesn't need too much threads.
      min-spare: 5
      max: 30

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${museifier.oauth2.issuer-uri}
          # Point to the URI containing the public key so that our Resource Server can verify the tokens’ integrity.
          jwk-set-uri: ${museifier.oauth2.jwk-uri}
  application:
    name: museum
  jpa:
    hibernate:
      # Disable automatic schema creation/update for production.
      ddl-auto: none
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

museifier:
  oauth2:
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}
    scopes: "openid"
    issuer-uri: ${OAUTH2_ISSUER_URI}
    token-uri: ${OAUTH2_TOKEN_URI}
    jwk-uri: ${OAUTH2_JWK_URI}