services:
  #  addok:
  #    image: etalab/addok
  #    container_name: ban-addok
  #    ports:
  #      - "7878:7878"
  #    volumes:
  #      - ./base_adresse_nationale/addok.conf:/etc/addok/addok.conf
  #      - ./base_adresse_nationale/addok.db:/data/addok.db
  #      - ./base_adresse_nationale/logs:/logs
  #    links:
  #      - addok-redis:redis
  #    environment:
  #      WORKERS: 1
  #      WORKER_TIMEOUT: 30
  #      LOG_QUERIES: 1
  #      LOG_NOT_FOUND: 1
  #      SLOW_QUERIES: 200
  #  addok-redis:
  #    image: etalab/addok-redis
  #    container_name: ban-addok-redis
  #    volumes:
  #      - ./base_adresse_nationale/dump.rdb:/data/dump.rdb


  keycloak-db:
    image: postgres:16.3-alpine3.18
    container_name: keycloak-db
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - "9001:5432"
    networks:
      - museifier_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak
    command: start

    environment:
      KC_HOSTNAME: https://auth.museifier.xingchen.fr
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # These 4 env disable HTTPS because it is handled by Nginx
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
    ports:
      - "9000:8080"
    volumes:
      - ./keycloak-themes:/opt/keycloak/providers/
    restart: unless-stopped
    depends_on:
      - keycloak-db
    networks:
      - museifier_network

  museifier-db:
    image: postgres:16.3-alpine3.18
    container_name: museifier-db
    restart: unless-stopped
    ports:
      - "9003:5432"
    environment:
      POSTGRES_DB: museifier
      POSTGRES_PASSWORD: ${MUSEIFIER_POSTGRES_PASSWORD}
    volumes:
      - museifier_db_data:/var/lib/postgresql/data
    #    healthcheck:
    #      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
    #      interval: 600s
    #      timeout: 10s
    #      retries: 5
    networks:
      - museifier_network

  museifier-api:
    image: hoshiix/museifier-api:latest
    container_name: museifier-api
    depends_on:
      - museifier-db
    ports:
      - "9004:8080"
    environment:
      DB_URL: jdbc:postgresql://museifier-db/museifier
      DB_USERNAME: ${MUSEIFIER_DB_USER}
      DB_PASSWORD: ${MUSEIFIER_DB_PASSWORD}
      OAUTH2_CLIENT_ID: ${MUSEIFIER_OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${MUSEIFIER_OAUTH2_CLIENT_SECRET}
      OAUTH2_ISSUER_URI: https://auth.museifier.xingchen.fr/realms/museifier
      OAUTH2_TOKEN_URI: https://auth.museifier.xingchen.fr/realms/museifier/protocol/openid-connect/token
      OAUTH2_JWK_URI: https://auth.museifier.xingchen.fr/realms/museifier/protocol/openid-connect/certs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - museifier_network

  museifier-web:
    image: hoshiix/museifier-web:latest
    container_name: museifier-web
    ports:
      - "9005:80"
    restart: unless-stopped
    networks:
      - museifier_network

networks:
  museifier_network:
volumes:
  keycloak_db_data:
  museifier_db_data: